---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mirrord-binding
  namespace: open
subjects:
  - kind: ServiceAccount
    name: open
    namespace: open
roleRef:
  kind: Role
  name: mirrord-role
  apiGroup: rbac.authorization.k8s.io
